---
author: "Gunjan"
output: html_document
---
  ```{r}
# transfer all .bed files in same directory and then do : grep "" .bed > simBed.txt. Do similarly for all the files

# use the following on command line
# Rscript *.md \
# -d coverage \
# -t variant type
# -s simBedfile \
# -p pindel \
# -c cnvnator \
# -l lumpy \
# -b svaba

# example as follows:

# cp /home/ggg256/scripts/simulation_del_analysis.Rmd .
# Rscript -e "library(knitr); knit('simulation_del_analysis.Rmd')" -p ${coverage}_pindel.txt \
# -c ${coverage}_cnv.txt -l ${coverage}_lumpy.txt -b ${coverage}_svaba.txt 
# -s ${path_to_simBed_file} -d ${coverage} -t ${variant_type}


```



```{r,echo=FALSE,warning=FALSE,results='hide',message=FALSE}
#source("https://bioconductor.org/biocLite.R")
#biocLite("GenomicRanges")
require(GenomicRanges)

#install.packages("tidyr",repos = "http://cran.us.r-project.org")
#install.packages("dplyr",repos = "http://cran.us.r-project.org")
library(tidyr)
library(dplyr)
library(optparse)
library(knitr)
```

```{r reading in the files,echo=FALSE}

option_list <- list(
  make_option(c("-d", "--depth"),action = "store",default = NULL,help="depth"),
  make_option(c("-t", "--type"),action = "store",default = NULL,help="variant type"),
  make_option(c("-b", "--svaba"),action = "store",default = NULL,help="svaba file"),
  make_option(c("-p", "--pindel"),action = "store",default = NULL,help="pindel file"),
  make_option(c("-c", "--cnvnator"),action = "store",default = NULL,help="cnvnator file"),
  make_option(c("-l", "--lumpy"),action = "store",default = NULL,help="lumpy file"),
  make_option(c("-s", "--simBed"),action = "store",default = NULL,help="simBed file"))

opt = parse_args(OptionParser(option_list=option_list))

simBed <- read.csv(opt$simBed,sep="\t",comment.char="",header=FALSE,stringsAsFactors = FALSE)
simBed <- (separate(data = simBed, col =V1, into = c("sim", "chrom"), sep = ".bed:"))

pind <- read.csv(opt$p,sep=" ",comment.char="",header=FALSE,stringsAsFactors = FALSE)
pind <- (separate(data = pind , col =V1, into = c("sim", "chrom"), sep = "_pindel.txt:"))
colnames(pind) <- c("V1","V2","V3","V4","V5","V6","V7")
p_provide <- pind[(pind$V2=="Provide"),]
pindel <- (pind %>% anti_join(p_provide))

cnvnator <- read.csv(opt$c, sep=" ",comment.char="",header=FALSE,stringsAsFactors = FALSE)
cnvnator <-(separate(data = cnvnator , col =V1, into = c("sim", "chrom"), sep = "_cnv.txt:"))

lumpy <- read.csv(opt$l, sep=" ",comment.char="",header=FALSE,stringsAsFactors = FALSE)
lumpy <-(separate(data = lumpy , col =V1, into = c("sim", "chrom"), sep = "_lumpy.txt:"))

svaba <- read.csv(opt$svaba, sep=",",comment.char="",header=FALSE,stringsAsFactors = FALSE)
svaba <- svaba[complete.cases(svaba),]
svaba <-(separate(data = svaba , col =V1, into = c("sim", "chrom"), sep = "_svaba.txt:"))
svaba$V4 <- abs(svaba$V2)+abs(svaba$V3)


depth=opt$d
type=opt$t
```



```{r,echo=FALSE,message=FALSE,eval=FALSE}
# setwd("~/Google Drive/simulations/simulation files to work with for Rcode")
setwd("~/Desktop/deletions")
depth="100X"
type="del"

simBed <- read.csv("sim_bed.txt",sep="\t",comment.char="",header=FALSE,stringsAsFactors = FALSE)
simBed <- (separate(data = simBed, col =V1, into = c("sim", "chrom"), sep = ".bed:"))

pind <- read.csv("pindel_100x.txt",sep=" ",comment.char="",header=FALSE,stringsAsFactors = FALSE)
pind <- (separate(data = pind , col =V1, into = c("sim", "chrom"), sep = "_pindel.txt:"))
colnames(pind) <- c("V1","V2","V3","V4","V5","V6","V7")
p_provide <- pind[(pind$V2=="Provide"),]
pindel <- (pind %>% anti_join(p_provide))

cnvnator <- read.csv("cnv_100x.txt", sep=" ",comment.char="",header=FALSE,stringsAsFactors = FALSE)
cnvnator <-(separate(data = cnvnator , col =V1, into = c("sim", "chrom"), sep = "_cnv.txt:"))

lumpy <- read.csv("lumpy_100x.txt", sep=" ",comment.char="",header=FALSE,stringsAsFactors = FALSE)
lumpy <-(separate(data = lumpy , col =V1, into = c("sim", "chrom"), sep = "_lumpy.txt:"))

svaba <- read.csv("svaba_100x.txt", sep=",",comment.char="",header=FALSE,stringsAsFactors = FALSE)
dim(svaba)
svaba <- svaba[complete.cases(svaba),]
dim(svaba)
svaba <-(separate(data = svaba , col =V1, into = c("sim", "chrom"), sep = "_svaba.txt:"))

svaba$V4 <- abs(svaba$V2)+abs(svaba$V3)
summary(svaba)

```


```{r data structures,echo=FALSE,message=FALSE}
colnames(pindel)<-c("sim","svtype","chrom.1","start","end","size","supporting.reads")
colnames(cnvnator)<-c("sim","svtype","chrom.1","start","end","size","normRDsignal")
colnames(lumpy)<-c("sim","svtype","chrom.1","start","end","size")
colnames(simBed) <- c("sim","chrom.1","start","chrom.2","end","svtype")
colnames(svaba) <- c("sim","chrom.1","start","size","end")


simBed$sim <- as.character(simBed$sim)
simBed$chrom.1 <- as.character(simBed$chrom.1)
simBed$chrom.2 <- as.character(simBed$chrom.2)
simBed$svtype <- as.character(simBed$svtype)
simBed$start <- as.integer(simBed$start)
simBed$end <- as.integer(simBed$end)

pindel$sim <- as.character(pindel$sim)
pindel$svtype <- as.character(pindel$svtype)
pindel$chrom.1 <- as.character(pindel$chrom.1)
pindel$start <- as.integer(pindel$start)
pindel$end <- as.integer(pindel$end)
pindel$size <- as.integer(pindel$size)
pindel$supporting.reads <- as.integer(pindel$supporting.reads)

cnvnator$sim <- as.character(cnvnator$sim)
cnvnator$svtype <- as.character(cnvnator$svtype)
cnvnator$chrom.1 <- as.character(cnvnator$chrom.1)
cnvnator$start <- as.integer(cnvnator$start)
cnvnator$end <- as.integer(cnvnator$end)
cnvnator$size <- as.integer(cnvnator$size)
cnvnator$normRDsignal <- as.numeric(cnvnator$normRDsignal)

lumpy$sim <- as.character(lumpy$sim)
lumpy$svtype <- as.character(lumpy$svtype)
lumpy$chrom.1 <- as.character(lumpy$chrom.1)
lumpy$start <- as.integer(lumpy$start)
lumpy$end <- as.integer(lumpy$end)
lumpy$size <- as.integer(abs(lumpy$size))

svaba$sim <- as.character(svaba$sim)
svaba$chrom.1 <- as.character(svaba$chrom.1)
svaba$start <- as.integer(svaba$start)
svaba$size <- as.integer(svaba$size)
svaba$end <- as.integer(svaba$end)

```

```{r filtering,echo=FALSE,message=FALSE}
pindel.del <- pindel[pindel$svtype=="D" & (pindel$size)>50 & (pindel$supporting.reads)>10 , ]
cnv.del <- cnvnator[cnvnator$svtype=="deletion" & (cnvnator$size)>50 & (cnvnator$normRDsignal) < 0.2 ,]
lumpy.del <- lumpy[lumpy$svtype=="DEL" & (abs(lumpy$size))>50 ,]
svaba.del <- svaba[abs(svaba$size)>50,]
sim.del <- simBed[simBed$svtype=="DEL",]
```


```{r Granges,warning=FALSE,echo=FALSE,message=FALSE}

gRange.object <- function (object){
  sim <- object$sim
  chr <- object$chrom.1 
  start <- object$start
  end <- object$end
  gR <- GRanges(seqnames = paste0(sim,chr), ranges = IRanges(start=start, end=end))
  return (gR)
}

scores <- function (query,subject,algorithm,coverage) {
  sim <- gRange.object(subject)
  test <- gRange.object(query)
  res <- countOverlaps(test,sim,type="any")
  TP <- length(res[!res==0])
  FP <- length(res[res==0])
  present <- dim(subject)[1]
  detected <- dim(query)[1]
  FDR <- round(((length(res[res==0]))/(length(res))),2) 
  precision <- round(((TP)/(TP+FP)),2)
  
  res1 <- countOverlaps(sim,test,type="any")
  FN <- (length(res1[res1==0]))
  sensitivity = round(((TP)/(TP+FN)),2)
  
  Fscore<-2*((precision*sensitivity)/(precision+sensitivity))
  Fscore <- round(Fscore,3)
  
  analysis <-t(as.data.frame(as.matrix(c(type,coverage,algorithm,present,detected,TP,FP,FN,FDR,precision,sensitivity,Fscore))))
  
  colnames(analysis) <- c("type","coverage","algorithm","#present","#detected","TP","FP","FN","FDR","precision","sensitivity","Fscore")
  return (analysis)
}

cnv.del.analysis<-scores(cnv.del,sim.del,"cnvnator",depth)
lumpy.del.analysis<-scores(lumpy.del,sim.del,"lumpy",depth)
pindel.del.analysis<-scores(pindel.del,sim.del,"pindel",depth)
svaba.del.analysis<-scores(svaba.del,sim.del,"svaba",depth)

if (dim(cnv.del.analysis)[2]!=0){
  final <- rbind(cnv.del.analysis)
}

if (dim(pindel.del.analysis)[2]!=0){
  final <- rbind(final,pindel.del.analysis)
}

if (dim(lumpy.del.analysis)[2]!=0){
  final <- rbind(final,lumpy.del.analysis)
}   

if (dim(svaba.del.analysis)[2]!=0){
  final <- rbind(final,svaba.del.analysis)
}  

rownames(final)<-c()
final <- as.data.frame(final)

final

write.csv(final, file = paste0(depth,type,".xls"))
```



```{r LG,warning=FALSE,message=FALSE,echo=FALSE}

pindel.GR <- gRange.object(pindel.del)
cnv.GR <- gRange.object(cnv.del)
lumpy.GR <- gRange.object(lumpy.del)
svaba.GR <- gRange.object(svaba.del)
sim.GR <- gRange.object(sim.del)

#length(pindel.GR)
#length(cnv.GR)
#length(lumpy.GR)
#length(sim.GR)
#length(svaba.GR)

pindel.vote <- sapply(countOverlaps(sim.GR,pindel.GR, type = "any"), function(x){if(x>0){return(2)}else{return(1)}})
cnv.vote <- sapply(countOverlaps(sim.GR,cnv.GR, type = "any"), function(x){if(x>0){return(2)}else{return(1)}})
lumpy.vote <- sapply(countOverlaps(sim.GR,lumpy.GR, type = "any"), function(x){if(x>0){return(2)}else{return(1)}})
svaba.vote <- sapply(countOverlaps(sim.GR,svaba.GR, type = "any"), function(x){if(x>0){return(2)}else{return(1)}})

votes <- NULL
votes <- as.data.frame(cbind(type,sim.del$sim, sim.del$chrom.1,sim.del$start,sim.del$end,
                             as.numeric(sim.del$end)-as.numeric(sim.del$start)))
colnames(votes) <- c("type","sim","chrom","start","end","size")

votes$pindel <- 0
votes$cnvnator <- 0
votes$lumpy <- 0
votes$svaba <- 0

if (length(pindel.vote)>1){
  votes$pindel <- pindel.vote
} else {
  votes$pindel <- 0
}

#head(votes)

if (length(cnv.vote)>1){
  votes$cnvnator <- cnv.vote
} else {
  votes$cnvnator <- 0
}

#head(votes)

if (length(lumpy.vote)>1){
  votes$lumpy <- lumpy.vote
} else {
  votes$lumpy  <- 0
}

if (length(svaba.vote)>1){
  votes$svaba <- svaba.vote
} else {
  votes$svaba <- 0
}

votes$pindel <- as.numeric(votes$pindel)
votes$lumpy <- as.numeric(votes$lumpy)
votes$cnvnator <- as.numeric(votes$cnvnator)
votes$svaba <- as.numeric(votes$svaba)

votes$pindel[votes$pindel==1] <- 0
votes$cnvnator[votes$cnvnator==1] <- 0
votes$lumpy[votes$lumpy==1] <- 0
votes$svaba[votes$svaba==1] <- 0

votes$pindel[votes$pindel==2] <- 1
votes$cnvnator[votes$cnvnator==2] <- 1
votes$lumpy[votes$lumpy==2] <- 1
votes$svaba[votes$svaba==2] <- 1

votes$call <- (votes$pindel + votes$cnvnator + votes$lumpy + votes$svaba)

votes <- votes[(order(votes$call,decreasing=TRUE)),]

MAIN.DF.1 <- data.frame()
MAIN.DF.1 <- subset(votes,select=c(pindel,cnvnator,lumpy,svaba))
MAIN.DF.1$truth <- 1


(votes)

write.csv(votes, file = paste0(depth,type,"_vote",".xls"))
```

Making a dataframe of all False positives


```{r Voting,warning=FALSE,message=FALSE,echo=FALSE,eval=FALSE}
pindel.GR <- gRange.object(pindel.del)
cnv.GR <- gRange.object(cnv.del)
lumpy.GR <- gRange.object(lumpy.del)
svaba.GR <- gRange.object(svaba.del)
sim.GR <- gRange.object(sim.del)

pindel.vote <- sapply(countOverlaps(pindel.GR,sim.GR,type = "any"), function(x){if(x>0){return(2)}else{return(1)}})
cnv.vote <- sapply(countOverlaps(cnv.GR,sim.GR, type = "any"), function(x){if(x>0){return(2)}else{return(1)}})
lumpy.vote <- sapply(countOverlaps(lumpy.GR,sim.GR, type = "any"), function(x){if(x>0){return(2)}else{return(1)}})
svaba.vote <- sapply(countOverlaps(svaba.GR,sim.GR,type = "any"), function(x){if(x>0){return(2)}else{return(1)}})




pindel.fp.1 <- pindel.del[which(pindel.vote==1),]
cnv.fp.1 <- cnv.del[which(cnv.vote==1),]
lumpy.fp.1 <- lumpy.del[which(lumpy.vote==1),]
svaba.fp.1 <- svaba.del[which(svaba.vote==1),]

pindel.fp <- subset(pindel.fp.1,select=c(sim,chrom.1,start,end))
cnv.fp <- subset(cnv.fp.1,select=c(sim,chrom.1,start,end))
lumpy.fp <- subset(lumpy.fp.1,select=c(sim,chrom.1,start,end))
svaba.fp <- subset(svaba.fp.1,select=c(sim,chrom.1,start,end))

MAIN.DF <- data.frame()

if (dim(pindel.fp)[1]>0) {
  fp.df.pindel <- pindel.fp
  n <- dim(pindel.fp)[1]
  fp.df.pindel$pindel <-rep(1,n)
  fp.df.pindel$cnvnator <- rep(0,n)
  fp.df.pindel$lumpy <- rep(0,n)
  fp.df.pindel$svaba <- rep(0,n)
  MAIN.DF <- rbind(MAIN.DF,fp.df.pindel)
}

if (dim(cnv.fp)[1]>0) {
  fp.df.cnv <- cnv.fp
  n <- dim(cnv.fp)[1]
  fp.df.cnv$pindel<- rep(0,n)
  fp.df.cnv$cnvnator <-rep(1,n)
  fp.df.cnv$lumpy <- rep(0,n)
  fp.df.cnv$svaba<- rep(0,n)
  MAIN.DF <- rbind(MAIN.DF,fp.df.cnv)
}

if (dim(lumpy.fp)[1]>0) {
  fp.df.lumpy <- lumpy.fp
  n <- dim(lumpy.fp)[1]
  fp.df.lumpy$pindel <- rep(0,n)
  fp.df.lumpy$cnvnator <- rep(0,n)
  fp.df.lumpy$lumpy <-rep(1,n)
  fp.df.lumpy$svaba <- rep(0,n)
  MAIN.DF <- rbind(MAIN.DF,fp.df.lumpy)
}

if (dim(svaba.fp)[1]>0) {
  fp.df.svaba <- svaba.fp
  n <- dim(svaba.fp)[1]
  fp.df.svaba$pindel <- rep(0,n)
  fp.df.svaba$cnvnator <- rep(0,n)
  fp.df.svaba$lumpy <- rep(0,n)
  fp.df.svaba$svaba <-rep(1,n)
  MAIN.DF <- rbind(MAIN.DF,fp.df.svaba)
}

MAIN.DF.2 <- data.frame()
MAIN.DF.2 <- subset(MAIN.DF,select=c(pindel,cnvnator,lumpy,svaba))
MAIN.DF.2$truth <- 0

LG.DATA <- data.frame()
LG.DATA <- as.data.frame(rbind(MAIN.DF.1,MAIN.DF.2))
LG.DATA$pindel <- as.factor(LG.DATA$pindel)
LG.DATA$cnvnator <- as.factor(LG.DATA$cnvnator)
LG.DATA$lumpy <- as.factor(LG.DATA$lumpy)
LG.DATA$svaba <- as.factor(LG.DATA$svaba)
LG.DATA$truth <- as.factor(LG.DATA$truth)

#x <- LG.DATA[complete.cases(LG.DATA),]

logit.reg <- glm(truth~.,data=LG.DATA,family = "binomial")
summary(logit.reg)

anova <- anova(logit.reg,test="Chisq")

```







```{r,echo=FALSE,message=FALSE,warning=FALSE,eval=FALSE}

## PINDEL
sim.del <- simBed[simBed$svtype=="DEL",]
size.reads <- NULL
for (x.size in seq(50,200,10)){
  for (x.reads in seq(2,50,2)){
    p <- pindel[pindel$svtype=="D" & (pindel$size)>=(x.size) & (pindel$supporting.reads)>=(x.reads) , ]
    final <- scores(p,sim.del,"pindel",depth)
    info <- as.data.frame(cbind(x.size,x.reads,final))
    print (c(x.size,x.reads))
    size.reads <- as.data.frame(rbind(size.reads,info))
  }
}
size.reads <- size.reads[size.reads$Fscore!="NaN",]
size.reads$FDR <- as.numeric(as.character(size.reads$FDR))
size.reads$Fscore <- as.numeric(as.character(size.reads$Fscore))
best.pindel <- size.reads[size.reads$Fscore==max(size.reads$Fscore) & size.reads$FDR==min(size.reads$FDR),]
#best.pindel

## CNVNATOR
size.reads <- NULL
info <- NULL
for (x.size in seq(50,200,10)){
  for (x.reads in seq(0.01,0.5,0.01)){
    c <- cnvnator[cnvnator$svtype=="deletion" & (cnvnator$size)>=x.size & (cnvnator$normRDsignal) <= x.reads ,]
    final <- scores(c,sim.del,"cnvnator",depth)
    info <- as.data.frame(cbind(x.size,x.reads,final))
    print (c(x.size,x.reads))
    size.reads <- as.data.frame(rbind(size.reads,info))
  }
}
size.reads <- size.reads[size.reads$Fscore!="NaN",]
size.reads$FDR <- as.numeric(as.character(size.reads$FDR))
size.reads$Fscore <- as.numeric(as.character(size.reads$Fscore))
best.cnvnator <- as.data.frame(size.reads[size.reads$Fscore==max(size.reads$Fscore) & size.reads$FDR==min(size.reads$FDR),])
#best.cnvnator

### LUMPY
size.reads <- NULL
info <- NULL
x.reads <- NULL
x.size <- NULL

for (x.size in seq(50,200,10)){
  
  l <- lumpy[lumpy$svtype=="DEL" & (lumpy$size)>=(x.size), ]
  final <- scores(l,sim.del,"lumpy",depth)
  zero <- 0
  info <- as.data.frame(cbind(x.size,zero,final))
  print (c(x.size))
  size.reads <- as.data.frame(rbind(size.reads,info))
}
size.reads <- size.reads[size.reads$Fscore!="NaN",]
size.reads$FDR <- as.numeric(as.character(size.reads$FDR))
size.reads$Fscore <- as.numeric(as.character(size.reads$Fscore))
best.lumpy <- size.reads[size.reads$Fscore==max(size.reads$Fscore) & size.reads$FDR==min(size.reads$FDR),]
#best.lumpy

best.parameters <- as.data.frame(rbind(best.pindel,best.cnvnator,best.lumpy))
rownames(best.parameters) <- NULL
colnames(best.parameters) <- c("size","supporting.reads","type","coverage","algorithm","#present","#detected","TP","FP","FN","FDR","precision","sensitivity","Fscore")

best.parameters

write.csv(best.parameters, file = paste0(depth,type,"_bestParameters",".xls"))

```

